apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  name: weather-app-podmonitoring
  namespace: weather-app
spec:
  selector:
    matchLabels:
      app: weather-app
  endpoints:
    - port: 8080
      path: /metrics
      interval: 60s